---
title: "hw2-mjclemen"
author: "Mandy Clemente"
date: "October 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown - load the following libraries

```{r}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(readxl)
require(stringr)
require(tools)
```

# Read in csv file, take first 500 records, and apply title caps to the columns that will be used in the maps

```{r}
# Read in spatial data
crimes <- read.csv("Crime_Incidents_in_the_Last_30_Days.csv")
crimes.shortened <- crimes[1:500,]
crimes$METHOD <- str_to_title(crimes$METHOD)
crimes$SHIFT <- str_to_title(crimes$SHIFT)
crimes$START_DATE <- as.Date(crimes$START_DATE)
crimes$DISTRICT <- as.factor(crimes$DISTRICT)
```

# Map with a layer of points

```{r}
# Creating colored icons for each shift during which a crime occurred
icons <- awesomeIconList(
  Day = makeAwesomeIcon(icon = "certificate", library = "glyphicon", markerColor = "orange", iconColor = "black"),
  Evening = makeAwesomeIcon(icon = "bed", library = "glyphicon", markerColor = "blue", iconColor = "black"),
  Midnight = makeAwesomeIcon(icon = "cloud", library = "glyphicon", markerColor = "black", iconColor = "white")
)

# Use icons in map to show where the crimes occurred throughout the day and night
leaflet(data = crimes) %>%
  addProviderTiles(providers$Stamen.TonerHybrid) %>%
  addAwesomeMarkers(lng = ~LONGITUDE, lat = ~LATITUDE,  icon = ~icons[str_trim(SHIFT)], popup = ~SHIFT)
```

# Map with a layer of lines
```{r}
new.crimes <- crimes[order(crimes$START_DATE),]

one.data <- new.crimes[(new.crimes$WARD == 1),]
two.data <- new.crimes[(new.crimes$WARD == 2),]
three.data <- new.crimes[(new.crimes$WARD == 3),]
four.data <- new.crimes[(new.crimes$WARD == 4),]
five.data <- new.crimes[(new.crimes$WARD == 5),]
six.data <- new.crimes[(new.crimes$WARD == 6),]
seven.data <- new.crimes[(new.crimes$WARD == 7),]
eight.data <- new.crimes[(new.crimes$WARD == 8),]

leaflet() %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addPolylines(data = one.data, lng = ~LONGITUDE, lat = ~LATITUDE, color = "red", group = ) %>%
  addPolylines(data = two.data, lng = ~LONGITUDE, lat = ~LATITUDE, color = "blue", group = ) %>%
  addPolylines(data = three.data, lng = ~LONGITUDE, lat = ~LATITUDE, color = "green", group = ) %>%
  addPolylines(data = four.data, lng = ~LONGITUDE, lat = ~LATITUDE, color = "purple", group = ) %>%
  addPolylines(data = five.data, lng = ~LONGITUDE, lat = ~LATITUDE, color = "pink", group = ) %>%
  addPolylines(data = six.data, lng = ~LONGITUDE, lat = ~LATITUDE, color = "orange", group = ) %>%
  addPolylines(data = seven.data, lng = ~LONGITUDE, lat = ~LATITUDE, color = "black", group = ) %>%
  addPolylines(data = eight.data, lng = ~LONGITUDE, lat = ~LATITUDE, color = "turquoise2", group = )
```
# Map with a layer of polygons
```{r, geojson}
# Read in geojson file
census.diversity <- readOGR("census-diversity.geojson")

# Create color palette to apply to polygons
color.palette <- colorNumeric("Purples", NULL)

# Create map to show the population in different regions and then the hispanic population compared to total
leaflet(census.diversity) %>%
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
    fillColor = ~color.palette(totpop10),
    popup = paste("Hispanic Population: ", census.diversity$hisppop_cy)) %>%
  addLegend(position = "topright", pal = color.palette, values = ~totpop10, opacity = 1.0,
            title = "Total Population in Region")
```
# Map with a variable which changes of the color of the elements or the marker with an accompanying legend
```{r}

# Custom Palette
time.of.day.colors <- colorFactor(
  palette = c('red', 'yellow', 'blue'),
  levels = c('Day', 'Evening', 'Midnight'))

leaflet(data = crimes) %>%
  addProviderTiles(providers$Esri.WorldStreetMap) %>%
  addCircleMarkers(data = crimes,
                   lng = ~LONGITUDE,
                   lat = ~LATITUDE,
                   radius = 2,
                   color = ~time.of.day.colors(SHIFT)) %>%
  addLegend(position = 'topright',
            pal = time.of.day.colors,
            values = crimes$SHIFT,
            title = 'Time of Day')
```
# Map with functioning layersControl()
```{r}
leaflet(crimes) %>%
  # Two different base groups
  addProviderTiles(providers$OpenStreetMap, group = "Open Street") %>%
  addProviderTiles(providers$Stamen, group = "Stamen") %>%
  # Two different layers
  addCircles(lng = ~LONGITUDE, lat = ~LATITUDE, radius = crimes$PSA, stroke = F, group = "PSA", popup = ~PSA) %>%
  addCircles(data = crimes, lng = ~LONGITUDE, lat = ~LATITUDE,
    fill = F, weight = 3, color = "red", group = "Circle Outline") %>%
  # Layers control
  addLayersControl(
    baseGroups = c("Open Street", "Stamen"),
    overlayGroups = c("PSA", "Circle Outline"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

